# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenFOAM(object):
    def setupUi(self, OpenFOAM):
        OpenFOAM.setObjectName("OpenFOAM")
        OpenFOAM.resize(1059, 731)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OpenFOAM.sizePolicy().hasHeightForWidth())
        OpenFOAM.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/OpenFOAM_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        OpenFOAM.setWindowIcon(icon)
        self.mainWindow = QtWidgets.QWidget(OpenFOAM)
        self.mainWindow.setObjectName("mainWindow")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainWindow)
        self.verticalLayout.setObjectName("verticalLayout")
        self.topSplitter = QtWidgets.QSplitter(self.mainWindow)
        self.topSplitter.setOrientation(QtCore.Qt.Horizontal)
        self.topSplitter.setObjectName("topSplitter")
        self.leftDomain = QtWidgets.QSplitter(self.topSplitter)
        self.leftDomain.setOrientation(QtCore.Qt.Vertical)
        self.leftDomain.setObjectName("leftDomain")
        self.pipLine = QtWidgets.QTreeWidget(self.leftDomain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pipLine.sizePolicy().hasHeightForWidth())
        self.pipLine.setSizePolicy(sizePolicy)
        self.pipLine.setSizeIncrement(QtCore.QSize(300, 0))
        self.pipLine.setObjectName("pipLine")
        item_0 = QtWidgets.QTreeWidgetItem(self.pipLine)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        item_0 = QtWidgets.QTreeWidgetItem(self.pipLine)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.pipLine)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.pipLine)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.pipLine)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.pipLine)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_0 = QtWidgets.QTreeWidgetItem(self.pipLine)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        self.propeties = QtWidgets.QTextBrowser(self.leftDomain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.propeties.sizePolicy().hasHeightForWidth())
        self.propeties.setSizePolicy(sizePolicy)
        self.propeties.setObjectName("propeties")
        self.rightDomain = QtWidgets.QSplitter(self.topSplitter)
        self.rightDomain.setOrientation(QtCore.Qt.Vertical)
        self.rightDomain.setObjectName("rightDomain")
        self.mainViewTabs = QtWidgets.QTabWidget(self.rightDomain)
        self.mainViewTabs.setObjectName("mainViewTabs")
        self.geoTab = QtWidgets.QWidget()
        self.geoTab.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        self.geoTab.setFont(font)
        self.geoTab.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.geoTab.setAccessibleName("")
        self.geoTab.setObjectName("geoTab")
        self.mainViewTabs.addTab(self.geoTab, "")
        self.monitorTab = QtWidgets.QWidget()
        self.monitorTab.setObjectName("monitorTab")
        self.mainViewTabs.addTab(self.monitorTab, "")
        self.output = QtWidgets.QTextBrowser(self.rightDomain)
        self.output.setObjectName("output")
        self.verticalLayout.addWidget(self.topSplitter)
        OpenFOAM.setCentralWidget(self.mainWindow)
        self.menuBar = QtWidgets.QMenuBar(OpenFOAM)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1059, 21))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuGeometry = QtWidgets.QMenu(self.menuBar)
        self.menuGeometry.setObjectName("menuGeometry")
        self.menuSolver = QtWidgets.QMenu(self.menuBar)
        self.menuSolver.setObjectName("menuSolver")
        self.menuPhysics = QtWidgets.QMenu(self.menuBar)
        self.menuPhysics.setObjectName("menuPhysics")
        self.menuHeat_transfer = QtWidgets.QMenu(self.menuPhysics)
        self.menuHeat_transfer.setObjectName("menuHeat_transfer")
        self.menuMaterial = QtWidgets.QMenu(self.menuBar)
        self.menuMaterial.setObjectName("menuMaterial")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        self.menuSetting = QtWidgets.QMenu(self.menuBar)
        self.menuSetting.setObjectName("menuSetting")
        OpenFOAM.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(OpenFOAM)
        self.toolBar.setObjectName("toolBar")
        OpenFOAM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.rightBar = QtWidgets.QToolBar(OpenFOAM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightBar.sizePolicy().hasHeightForWidth())
        self.rightBar.setSizePolicy(sizePolicy)
        self.rightBar.setObjectName("rightBar")
        OpenFOAM.addToolBar(QtCore.Qt.RightToolBarArea, self.rightBar)
        self.statusBar = QtWidgets.QStatusBar(OpenFOAM)
        self.statusBar.setBaseSize(QtCore.QSize(0, 50))
        self.statusBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.statusBar.setObjectName("statusBar")
        OpenFOAM.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(OpenFOAM)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionWrite = QtWidgets.QAction(OpenFOAM)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWrite.setIcon(icon2)
        self.actionWrite.setObjectName("actionWrite")
        self.actionQuit = QtWidgets.QAction(OpenFOAM)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTurbulence = QtWidgets.QAction(OpenFOAM)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/turbulence.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTurbulence.setIcon(icon4)
        self.actionTurbulence.setObjectName("actionTurbulence")
        self.actionMRF = QtWidgets.QAction(OpenFOAM)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/MRF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMRF.setIcon(icon5)
        self.actionMRF.setObjectName("actionMRF")
        self.actionDynamic_Mesh = QtWidgets.QAction(OpenFOAM)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/dynamicMesh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDynamic_Mesh.setIcon(icon6)
        self.actionDynamic_Mesh.setObjectName("actionDynamic_Mesh")
        self.actionRadiation = QtWidgets.QAction(OpenFOAM)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/radiation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRadiation.setIcon(icon7)
        self.actionRadiation.setObjectName("actionRadiation")
        self.actionMultiphase = QtWidgets.QAction(OpenFOAM)
        self.actionMultiphase.setObjectName("actionMultiphase")
        self.actionfvSchemes = QtWidgets.QAction(OpenFOAM)
        self.actionfvSchemes.setObjectName("actionfvSchemes")
        self.actionfvOptions = QtWidgets.QAction(OpenFOAM)
        self.actionfvOptions.setObjectName("actionfvOptions")
        self.actionControl = QtWidgets.QAction(OpenFOAM)
        self.actionControl.setObjectName("actionControl")
        self.actionz = QtWidgets.QAction(OpenFOAM)
        self.actionz.setObjectName("actionz")
        self.actionSplit_region = QtWidgets.QAction(OpenFOAM)
        self.actionSplit_region.setObjectName("actionSplit_region")
        self.actionMuti_region = QtWidgets.QAction(OpenFOAM)
        self.actionMuti_region.setObjectName("actionMuti_region")
        self.actionFluid = QtWidgets.QAction(OpenFOAM)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/waterDrop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFluid.setIcon(icon8)
        self.actionFluid.setObjectName("actionFluid")
        self.actionSolid = QtWidgets.QAction(OpenFOAM)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSolid.setIcon(icon9)
        self.actionSolid.setObjectName("actionSolid")
        self.actionNote = QtWidgets.QAction(OpenFOAM)
        self.actionNote.setObjectName("actionNote")
        self.actionRun = QtWidgets.QAction(OpenFOAM)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon10)
        self.actionRun.setObjectName("actionRun")
        self.actionStop = QtWidgets.QAction(OpenFOAM)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon11)
        self.actionStop.setObjectName("actionStop")
        self.actionPostProcess = QtWidgets.QAction(OpenFOAM)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/paraview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPostProcess.setIcon(icon12)
        self.actionPostProcess.setObjectName("actionPostProcess")
        self.actionAlign_X = QtWidgets.QAction(OpenFOAM)
        self.actionAlign_X.setObjectName("actionAlign_X")
        self.actionAlign_X_2 = QtWidgets.QAction(OpenFOAM)
        self.actionAlign_X_2.setObjectName("actionAlign_X_2")
        self.actionAlign_Y = QtWidgets.QAction(OpenFOAM)
        self.actionAlign_Y.setObjectName("actionAlign_Y")
        self.actionAligh_Y = QtWidgets.QAction(OpenFOAM)
        self.actionAligh_Y.setObjectName("actionAligh_Y")
        self.actionAligh_Z = QtWidgets.QAction(OpenFOAM)
        self.actionAligh_Z.setObjectName("actionAligh_Z")
        self.actionAligh_Z_2 = QtWidgets.QAction(OpenFOAM)
        self.actionAligh_Z_2.setObjectName("actionAligh_Z_2")
        self.actionAlign_45 = QtWidgets.QAction(OpenFOAM)
        self.actionAlign_45.setObjectName("actionAlign_45")
        self.actionPatches = QtWidgets.QAction(OpenFOAM)
        self.actionPatches.setObjectName("actionPatches")
        self.actionDefault_Folder = QtWidgets.QAction(OpenFOAM)
        self.actionDefault_Folder.setObjectName("actionDefault_Folder")
        self.actionParaview_Path = QtWidgets.QAction(OpenFOAM)
        self.actionParaview_Path.setObjectName("actionParaview_Path")
        self.actionTools = QtWidgets.QAction(OpenFOAM)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap("images/setting.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTools.setIcon(icon13)
        self.actionTools.setObjectName("actionTools")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionWrite)
        self.menuFile.addAction(self.actionQuit)
        self.menuGeometry.addAction(self.actionz)
        self.menuGeometry.addAction(self.actionPatches)
        self.menuSolver.addAction(self.actionfvSchemes)
        self.menuSolver.addAction(self.actionfvOptions)
        self.menuSolver.addAction(self.actionControl)
        self.menuSolver.addAction(self.actionRun)
        self.menuSolver.addAction(self.actionStop)
        self.menuSolver.addAction(self.actionPostProcess)
        self.menuHeat_transfer.addAction(self.actionMuti_region)
        self.menuPhysics.addAction(self.actionTurbulence)
        self.menuPhysics.addAction(self.actionMRF)
        self.menuPhysics.addAction(self.actionDynamic_Mesh)
        self.menuPhysics.addAction(self.actionRadiation)
        self.menuPhysics.addAction(self.actionMultiphase)
        self.menuPhysics.addAction(self.menuHeat_transfer.menuAction())
        self.menuMaterial.addAction(self.actionFluid)
        self.menuMaterial.addAction(self.actionSolid)
        self.menuHelp.addAction(self.actionNote)
        self.menuView.addAction(self.actionAlign_X)
        self.menuView.addAction(self.actionAlign_X_2)
        self.menuView.addAction(self.actionAlign_Y)
        self.menuView.addAction(self.actionAligh_Y)
        self.menuView.addAction(self.actionAligh_Z)
        self.menuView.addAction(self.actionAligh_Z_2)
        self.menuView.addAction(self.actionAlign_45)
        self.menuSetting.addAction(self.actionTools)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuGeometry.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuPhysics.menuAction())
        self.menuBar.addAction(self.menuMaterial.menuAction())
        self.menuBar.addAction(self.menuSolver.menuAction())
        self.menuBar.addAction(self.menuSetting.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionWrite)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionTools)
        self.toolBar.addAction(self.actionPostProcess)
        self.toolBar.addAction(self.actionQuit)
        self.rightBar.addSeparator()
        self.rightBar.addAction(self.actionControl)
        self.rightBar.addAction(self.actionz)

        self.retranslateUi(OpenFOAM)
        self.mainViewTabs.setCurrentIndex(1)
        self.actionQuit.triggered.connect(OpenFOAM.close)
        QtCore.QMetaObject.connectSlotsByName(OpenFOAM)

    def retranslateUi(self, OpenFOAM):
        _translate = QtCore.QCoreApplication.translate
        OpenFOAM.setWindowTitle(_translate("OpenFOAM", "OpenFOAM"))
        self.pipLine.headerItem().setText(0, _translate("OpenFOAM", "Property"))
        self.pipLine.headerItem().setText(1, _translate("OpenFOAM", "Value"))
        __sortingEnabled = self.pipLine.isSortingEnabled()
        self.pipLine.setSortingEnabled(False)
        self.pipLine.topLevelItem(0).setText(0, _translate("OpenFOAM", "Geometry"))
        self.pipLine.topLevelItem(0).child(0).setText(0, _translate("OpenFOAM", "Region1"))
        self.pipLine.topLevelItem(0).child(0).child(0).setText(0, _translate("OpenFOAM", "cellZone1"))
        self.pipLine.topLevelItem(0).child(0).child(1).setText(0, _translate("OpenFOAM", "cellZone2"))
        self.pipLine.topLevelItem(0).child(0).child(2).setText(0, _translate("OpenFOAM", "Patch"))
        self.pipLine.topLevelItem(0).child(1).setText(0, _translate("OpenFOAM", "Region2"))
        self.pipLine.topLevelItem(0).child(1).child(0).setText(0, _translate("OpenFOAM", "Patch1"))
        self.pipLine.topLevelItem(0).child(1).child(1).setText(0, _translate("OpenFOAM", "cellZone1"))
        self.pipLine.topLevelItem(0).child(1).child(2).setText(0, _translate("OpenFOAM", "Patch2"))
        self.pipLine.topLevelItem(0).child(1).child(3).setText(0, _translate("OpenFOAM", "cellZone2"))
        self.pipLine.topLevelItem(1).setText(0, _translate("OpenFOAM", "Physics"))
        self.pipLine.topLevelItem(1).child(0).setText(0, _translate("OpenFOAM", "Turbulence"))
        self.pipLine.topLevelItem(1).child(1).setText(0, _translate("OpenFOAM", "MRF"))
        self.pipLine.topLevelItem(1).child(2).setText(0, _translate("OpenFOAM", "DynamicMesh"))
        self.pipLine.topLevelItem(1).child(3).setText(0, _translate("OpenFOAM", "Multiphase"))
        self.pipLine.topLevelItem(1).child(4).setText(0, _translate("OpenFOAM", "Heat"))
        self.pipLine.topLevelItem(1).child(5).setText(0, _translate("OpenFOAM", "Radiation"))
        self.pipLine.topLevelItem(2).setText(0, _translate("OpenFOAM", "Material"))
        self.pipLine.topLevelItem(2).child(0).setText(0, _translate("OpenFOAM", "Viscosity"))
        self.pipLine.topLevelItem(2).child(1).setText(0, _translate("OpenFOAM", "Heat Conductivity"))
        self.pipLine.topLevelItem(2).child(2).setText(0, _translate("OpenFOAM", "Specific Heat"))
        self.pipLine.topLevelItem(2).child(3).setText(0, _translate("OpenFOAM", "Density"))
        self.pipLine.topLevelItem(3).setText(0, _translate("OpenFOAM", "fvSchemes"))
        self.pipLine.topLevelItem(3).child(0).setText(0, _translate("OpenFOAM", "ddt"))
        self.pipLine.topLevelItem(3).child(1).setText(0, _translate("OpenFOAM", "div"))
        self.pipLine.topLevelItem(3).child(2).setText(0, _translate("OpenFOAM", "laplacian"))
        self.pipLine.topLevelItem(4).setText(0, _translate("OpenFOAM", "fvSolution"))
        self.pipLine.topLevelItem(4).child(0).setText(0, _translate("OpenFOAM", "solver"))
        self.pipLine.topLevelItem(4).child(1).setText(0, _translate("OpenFOAM", "residual"))
        self.pipLine.topLevelItem(4).child(2).setText(0, _translate("OpenFOAM", "relaxation"))
        self.pipLine.topLevelItem(5).setText(0, _translate("OpenFOAM", "fvOption"))
        self.pipLine.topLevelItem(5).child(0).setText(0, _translate("OpenFOAM", "Heat Source"))
        self.pipLine.topLevelItem(5).child(1).setText(0, _translate("OpenFOAM", "Temp limit"))
        self.pipLine.topLevelItem(6).setText(0, _translate("OpenFOAM", "Solver"))
        self.pipLine.topLevelItem(6).child(0).setText(0, _translate("OpenFOAM", "Application"))
        self.pipLine.topLevelItem(6).child(1).setText(0, _translate("OpenFOAM", "StartFrom"))
        self.pipLine.topLevelItem(6).child(2).setText(0, _translate("OpenFOAM", "TimeStep"))
        self.pipLine.topLevelItem(6).child(3).setText(0, _translate("OpenFOAM", "Write Interval"))
        self.pipLine.topLevelItem(6).child(4).setText(0, _translate("OpenFOAM", "End Time"))
        self.pipLine.topLevelItem(6).child(5).setText(0, _translate("OpenFOAM", "Change ON-FLY"))
        self.pipLine.topLevelItem(6).child(6).setText(0, _translate("OpenFOAM", "adjust Time step"))
        self.pipLine.topLevelItem(6).child(7).setText(0, _translate("OpenFOAM", "maxCo"))
        self.pipLine.topLevelItem(6).child(8).setText(0, _translate("OpenFOAM", "Function"))
        self.pipLine.setSortingEnabled(__sortingEnabled)
        self.propeties.setHtml(_translate("OpenFOAM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.mainViewTabs.setTabText(self.mainViewTabs.indexOf(self.geoTab), _translate("OpenFOAM", "Geometry"))
        self.mainViewTabs.setTabText(self.mainViewTabs.indexOf(self.monitorTab), _translate("OpenFOAM", "Monitor"))
        self.menuFile.setTitle(_translate("OpenFOAM", "File"))
        self.menuGeometry.setTitle(_translate("OpenFOAM", "Geometry"))
        self.menuSolver.setTitle(_translate("OpenFOAM", "Solver"))
        self.menuPhysics.setTitle(_translate("OpenFOAM", "Physics"))
        self.menuHeat_transfer.setTitle(_translate("OpenFOAM", "Heat transfer"))
        self.menuMaterial.setTitle(_translate("OpenFOAM", "Material"))
        self.menuHelp.setTitle(_translate("OpenFOAM", "Help"))
        self.menuView.setTitle(_translate("OpenFOAM", "View"))
        self.menuSetting.setTitle(_translate("OpenFOAM", "Setting"))
        self.toolBar.setWindowTitle(_translate("OpenFOAM", "toolBar"))
        self.rightBar.setWindowTitle(_translate("OpenFOAM", "toolBar_2"))
        self.statusBar.setToolTip(_translate("OpenFOAM", "To see if it exists"))
        self.actionOpen.setText(_translate("OpenFOAM", "Open"))
        self.actionWrite.setText(_translate("OpenFOAM", "Write"))
        self.actionQuit.setText(_translate("OpenFOAM", "Quit"))
        self.actionTurbulence.setText(_translate("OpenFOAM", "Turbulence"))
        self.actionMRF.setText(_translate("OpenFOAM", "MRF"))
        self.actionDynamic_Mesh.setText(_translate("OpenFOAM", "Dynamic Mesh"))
        self.actionRadiation.setText(_translate("OpenFOAM", "Radiation"))
        self.actionMultiphase.setText(_translate("OpenFOAM", "Multiphase"))
        self.actionfvSchemes.setText(_translate("OpenFOAM", "fvSchemes"))
        self.actionfvOptions.setText(_translate("OpenFOAM", "fvOptions"))
        self.actionControl.setText(_translate("OpenFOAM", "Control "))
        self.actionz.setText(_translate("OpenFOAM", "Domain"))
        self.actionSplit_region.setText(_translate("OpenFOAM", "Split region"))
        self.actionMuti_region.setText(_translate("OpenFOAM", "Muti region"))
        self.actionFluid.setText(_translate("OpenFOAM", "Fluid"))
        self.actionSolid.setText(_translate("OpenFOAM", "Solid"))
        self.actionNote.setText(_translate("OpenFOAM", "Note"))
        self.actionRun.setText(_translate("OpenFOAM", "Run"))
        self.actionStop.setText(_translate("OpenFOAM", "Stop"))
        self.actionPostProcess.setText(_translate("OpenFOAM", "PostProcess"))
        self.actionAlign_X.setText(_translate("OpenFOAM", "Align X+"))
        self.actionAlign_X_2.setText(_translate("OpenFOAM", "Align X-"))
        self.actionAlign_Y.setText(_translate("OpenFOAM", "Align Y+"))
        self.actionAligh_Y.setText(_translate("OpenFOAM", "Aligh Y-"))
        self.actionAligh_Z.setText(_translate("OpenFOAM", "Aligh Z+"))
        self.actionAligh_Z_2.setText(_translate("OpenFOAM", "Aligh Z-"))
        self.actionAlign_45.setText(_translate("OpenFOAM", "Align 45°"))
        self.actionPatches.setText(_translate("OpenFOAM", "Patches"))
        self.actionDefault_Folder.setText(_translate("OpenFOAM", "Default Folder"))
        self.actionParaview_Path.setText(_translate("OpenFOAM", "Paraview Path"))
        self.actionTools.setText(_translate("OpenFOAM", "Tools"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OpenFOAM = QtWidgets.QMainWindow()
    ui = Ui_OpenFOAM()
    ui.setupUi(OpenFOAM)
    OpenFOAM.show()
    sys.exit(app.exec_())
