# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ccm.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OpenFOAM(object):
    def setupUi(self, OpenFOAM):
        OpenFOAM.setObjectName("OpenFOAM")
        OpenFOAM.resize(1059, 731)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(6)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(OpenFOAM.sizePolicy().hasHeightForWidth())
        OpenFOAM.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/OpenFOAM_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        OpenFOAM.setWindowIcon(icon)
        self.Window = QtWidgets.QWidget(OpenFOAM)
        self.Window.setObjectName("Window")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Window)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter_2 = QtWidgets.QSplitter(self.Window)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.leftDomain = QtWidgets.QSplitter(self.splitter_2)
        self.leftDomain.setOrientation(QtCore.Qt.Vertical)
        self.leftDomain.setObjectName("leftDomain")
        self.pipLine = QtWidgets.QListWidget(self.leftDomain)
        self.pipLine.setObjectName("pipLine")
        item = QtWidgets.QListWidgetItem()
        self.pipLine.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.pipLine.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.pipLine.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.pipLine.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.pipLine.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.pipLine.addItem(item)
        self.propeties = QtWidgets.QTextBrowser(self.leftDomain)
        self.propeties.setObjectName("propeties")
        self.MainWindow = QtWidgets.QSplitter(self.splitter_2)
        self.MainWindow.setOrientation(QtCore.Qt.Vertical)
        self.MainWindow.setObjectName("MainWindow")
        self.tabWidget = QtWidgets.QTabWidget(self.MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName("tabWidget")
        self.Geometry = QtWidgets.QWidget()
        self.Geometry.setMaximumSize(QtCore.QSize(486, 52))
        self.Geometry.setObjectName("Geometry")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Geometry)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.geoFrame = QtWidgets.QFrame(self.Geometry)
        self.geoFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.geoFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.geoFrame.setObjectName("geoFrame")
        self.verticalLayout_2.addWidget(self.geoFrame)
        self.tabWidget.addTab(self.Geometry, "")
        self.Monitor = QtWidgets.QWidget()
        self.Monitor.setMaximumSize(QtCore.QSize(486, 52))
        self.Monitor.setObjectName("Monitor")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Monitor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.monitorFrame = QtWidgets.QFrame(self.Monitor)
        self.monitorFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.monitorFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.monitorFrame.setObjectName("monitorFrame")
        self.verticalLayout.addWidget(self.monitorFrame)
        self.tabWidget.addTab(self.Monitor, "")
        self.output = QtWidgets.QTextBrowser(self.MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output.sizePolicy().hasHeightForWidth())
        self.output.setSizePolicy(sizePolicy)
        self.output.setSizeIncrement(QtCore.QSize(0, 20))
        self.output.setBaseSize(QtCore.QSize(0, 20))
        self.output.setObjectName("output")
        self.horizontalLayout.addWidget(self.splitter_2)
        OpenFOAM.setCentralWidget(self.Window)
        self.menuBar = QtWidgets.QMenuBar(OpenFOAM)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1059, 22))
        self.menuBar.setObjectName("menuBar")
        self.menuFile = QtWidgets.QMenu(self.menuBar)
        self.menuFile.setObjectName("menuFile")
        self.menuGeometry = QtWidgets.QMenu(self.menuBar)
        self.menuGeometry.setObjectName("menuGeometry")
        self.menuSolver = QtWidgets.QMenu(self.menuBar)
        self.menuSolver.setObjectName("menuSolver")
        self.menuPhysics = QtWidgets.QMenu(self.menuBar)
        self.menuPhysics.setObjectName("menuPhysics")
        self.menuHeat_transfer = QtWidgets.QMenu(self.menuPhysics)
        self.menuHeat_transfer.setObjectName("menuHeat_transfer")
        self.menuMaterial = QtWidgets.QMenu(self.menuBar)
        self.menuMaterial.setObjectName("menuMaterial")
        self.menuHelp = QtWidgets.QMenu(self.menuBar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menuBar)
        self.menuView.setObjectName("menuView")
        OpenFOAM.setMenuBar(self.menuBar)
        self.toolBar = QtWidgets.QToolBar(OpenFOAM)
        self.toolBar.setObjectName("toolBar")
        OpenFOAM.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.rightBar = QtWidgets.QToolBar(OpenFOAM)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightBar.sizePolicy().hasHeightForWidth())
        self.rightBar.setSizePolicy(sizePolicy)
        self.rightBar.setObjectName("rightBar")
        OpenFOAM.addToolBar(QtCore.Qt.RightToolBarArea, self.rightBar)
        self.statusBar = QtWidgets.QStatusBar(OpenFOAM)
        self.statusBar.setBaseSize(QtCore.QSize(0, 50))
        self.statusBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.statusBar.setObjectName("statusBar")
        OpenFOAM.setStatusBar(self.statusBar)
        self.actionOpen = QtWidgets.QAction(OpenFOAM)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/open.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOpen.setIcon(icon1)
        self.actionOpen.setObjectName("actionOpen")
        self.actionWrite = QtWidgets.QAction(OpenFOAM)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/save.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWrite.setIcon(icon2)
        self.actionWrite.setObjectName("actionWrite")
        self.actionQuit = QtWidgets.QAction(OpenFOAM)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/exit.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionQuit.setIcon(icon3)
        self.actionQuit.setObjectName("actionQuit")
        self.actionTurbulence = QtWidgets.QAction(OpenFOAM)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/turbulence.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionTurbulence.setIcon(icon4)
        self.actionTurbulence.setObjectName("actionTurbulence")
        self.actionMRF = QtWidgets.QAction(OpenFOAM)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("images/MRF.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMRF.setIcon(icon5)
        self.actionMRF.setObjectName("actionMRF")
        self.actionDynamic_Mesh = QtWidgets.QAction(OpenFOAM)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("images/dynamicMesh.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDynamic_Mesh.setIcon(icon6)
        self.actionDynamic_Mesh.setObjectName("actionDynamic_Mesh")
        self.actionRadiation = QtWidgets.QAction(OpenFOAM)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap("images/radiation.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRadiation.setIcon(icon7)
        self.actionRadiation.setObjectName("actionRadiation")
        self.actionMultiphase = QtWidgets.QAction(OpenFOAM)
        self.actionMultiphase.setObjectName("actionMultiphase")
        self.actionfvSchemes = QtWidgets.QAction(OpenFOAM)
        self.actionfvSchemes.setObjectName("actionfvSchemes")
        self.actionfvOptions = QtWidgets.QAction(OpenFOAM)
        self.actionfvOptions.setObjectName("actionfvOptions")
        self.actionControl = QtWidgets.QAction(OpenFOAM)
        self.actionControl.setObjectName("actionControl")
        self.actionz = QtWidgets.QAction(OpenFOAM)
        self.actionz.setObjectName("actionz")
        self.actionSplit_region = QtWidgets.QAction(OpenFOAM)
        self.actionSplit_region.setObjectName("actionSplit_region")
        self.actionMuti_region = QtWidgets.QAction(OpenFOAM)
        self.actionMuti_region.setObjectName("actionMuti_region")
        self.actionFluid = QtWidgets.QAction(OpenFOAM)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap("images/waterDrop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionFluid.setIcon(icon8)
        self.actionFluid.setObjectName("actionFluid")
        self.actionSolid = QtWidgets.QAction(OpenFOAM)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap("images/solid.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSolid.setIcon(icon9)
        self.actionSolid.setObjectName("actionSolid")
        self.actionNote = QtWidgets.QAction(OpenFOAM)
        self.actionNote.setObjectName("actionNote")
        self.actionRun = QtWidgets.QAction(OpenFOAM)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap("images/start.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRun.setIcon(icon10)
        self.actionRun.setObjectName("actionRun")
        self.actionStop = QtWidgets.QAction(OpenFOAM)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap("images/stop.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionStop.setIcon(icon11)
        self.actionStop.setObjectName("actionStop")
        self.actionPostProcess = QtWidgets.QAction(OpenFOAM)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap("images/paraview.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionPostProcess.setIcon(icon12)
        self.actionPostProcess.setObjectName("actionPostProcess")
        self.actionAlign_X = QtWidgets.QAction(OpenFOAM)
        self.actionAlign_X.setObjectName("actionAlign_X")
        self.actionAlign_X_2 = QtWidgets.QAction(OpenFOAM)
        self.actionAlign_X_2.setObjectName("actionAlign_X_2")
        self.actionAlign_Y = QtWidgets.QAction(OpenFOAM)
        self.actionAlign_Y.setObjectName("actionAlign_Y")
        self.actionAligh_Y = QtWidgets.QAction(OpenFOAM)
        self.actionAligh_Y.setObjectName("actionAligh_Y")
        self.actionAligh_Z = QtWidgets.QAction(OpenFOAM)
        self.actionAligh_Z.setObjectName("actionAligh_Z")
        self.actionAligh_Z_2 = QtWidgets.QAction(OpenFOAM)
        self.actionAligh_Z_2.setObjectName("actionAligh_Z_2")
        self.actionAlign_45 = QtWidgets.QAction(OpenFOAM)
        self.actionAlign_45.setObjectName("actionAlign_45")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionWrite)
        self.menuFile.addAction(self.actionQuit)
        self.menuGeometry.addAction(self.actionz)
        self.menuSolver.addAction(self.actionfvSchemes)
        self.menuSolver.addAction(self.actionfvOptions)
        self.menuSolver.addAction(self.actionControl)
        self.menuSolver.addAction(self.actionRun)
        self.menuSolver.addAction(self.actionStop)
        self.menuSolver.addAction(self.actionPostProcess)
        self.menuHeat_transfer.addAction(self.actionMuti_region)
        self.menuPhysics.addAction(self.actionTurbulence)
        self.menuPhysics.addAction(self.actionMRF)
        self.menuPhysics.addAction(self.actionDynamic_Mesh)
        self.menuPhysics.addAction(self.actionRadiation)
        self.menuPhysics.addAction(self.actionMultiphase)
        self.menuPhysics.addAction(self.menuHeat_transfer.menuAction())
        self.menuMaterial.addAction(self.actionFluid)
        self.menuMaterial.addAction(self.actionSolid)
        self.menuHelp.addAction(self.actionNote)
        self.menuView.addAction(self.actionAlign_X)
        self.menuView.addAction(self.actionAlign_X_2)
        self.menuView.addAction(self.actionAlign_Y)
        self.menuView.addAction(self.actionAligh_Y)
        self.menuView.addAction(self.actionAligh_Z)
        self.menuView.addAction(self.actionAligh_Z_2)
        self.menuView.addAction(self.actionAlign_45)
        self.menuBar.addAction(self.menuFile.menuAction())
        self.menuBar.addAction(self.menuGeometry.menuAction())
        self.menuBar.addAction(self.menuView.menuAction())
        self.menuBar.addAction(self.menuPhysics.menuAction())
        self.menuBar.addAction(self.menuMaterial.menuAction())
        self.menuBar.addAction(self.menuSolver.menuAction())
        self.menuBar.addAction(self.menuHelp.menuAction())
        self.toolBar.addSeparator()
        self.toolBar.addAction(self.actionOpen)
        self.toolBar.addAction(self.actionWrite)
        self.toolBar.addAction(self.actionRun)
        self.toolBar.addAction(self.actionStop)
        self.toolBar.addAction(self.actionQuit)
        self.toolBar.addAction(self.actionPostProcess)
        self.rightBar.addSeparator()
        self.rightBar.addAction(self.actionControl)
        self.rightBar.addAction(self.actionz)

        self.retranslateUi(OpenFOAM)
        self.tabWidget.setCurrentIndex(0)
        self.actionQuit.triggered.connect(OpenFOAM.close)
        QtCore.QMetaObject.connectSlotsByName(OpenFOAM)

    def retranslateUi(self, OpenFOAM):
        _translate = QtCore.QCoreApplication.translate
        OpenFOAM.setWindowTitle(_translate("OpenFOAM", "OpenFOAM"))
        __sortingEnabled = self.pipLine.isSortingEnabled()
        self.pipLine.setSortingEnabled(False)
        item = self.pipLine.item(0)
        item.setText(_translate("OpenFOAM", "Geometry"))
        item = self.pipLine.item(1)
        item.setText(_translate("OpenFOAM", "Physics"))
        item = self.pipLine.item(2)
        item.setText(_translate("OpenFOAM", "Material"))
        item = self.pipLine.item(3)
        item.setText(_translate("OpenFOAM", "fvSchemes"))
        item = self.pipLine.item(4)
        item.setText(_translate("OpenFOAM", "fvOption"))
        item = self.pipLine.item(5)
        item.setText(_translate("OpenFOAM", "Solver"))
        self.pipLine.setSortingEnabled(__sortingEnabled)
        self.propeties.setHtml(_translate("OpenFOAM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Geometry), _translate("OpenFOAM", "Geometry"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Monitor), _translate("OpenFOAM", "Monitor"))
        self.output.setHtml(_translate("OpenFOAM", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">output domain</p></body></html>"))
        self.menuFile.setTitle(_translate("OpenFOAM", "File"))
        self.menuGeometry.setTitle(_translate("OpenFOAM", "Geometry"))
        self.menuSolver.setTitle(_translate("OpenFOAM", "Solver"))
        self.menuPhysics.setTitle(_translate("OpenFOAM", "Physics"))
        self.menuHeat_transfer.setTitle(_translate("OpenFOAM", "Heat transfer"))
        self.menuMaterial.setTitle(_translate("OpenFOAM", "Material"))
        self.menuHelp.setTitle(_translate("OpenFOAM", "Help"))
        self.menuView.setTitle(_translate("OpenFOAM", "View"))
        self.toolBar.setWindowTitle(_translate("OpenFOAM", "toolBar"))
        self.rightBar.setWindowTitle(_translate("OpenFOAM", "toolBar_2"))
        self.statusBar.setToolTip(_translate("OpenFOAM", "To see if it exists"))
        self.actionOpen.setText(_translate("OpenFOAM", "Open"))
        self.actionWrite.setText(_translate("OpenFOAM", "Write"))
        self.actionQuit.setText(_translate("OpenFOAM", "Quit"))
        self.actionTurbulence.setText(_translate("OpenFOAM", "Turbulence"))
        self.actionMRF.setText(_translate("OpenFOAM", "MRF"))
        self.actionDynamic_Mesh.setText(_translate("OpenFOAM", "Dynamic Mesh"))
        self.actionRadiation.setText(_translate("OpenFOAM", "Radiation"))
        self.actionMultiphase.setText(_translate("OpenFOAM", "Multiphase"))
        self.actionfvSchemes.setText(_translate("OpenFOAM", "fvSchemes"))
        self.actionfvOptions.setText(_translate("OpenFOAM", "fvOptions"))
        self.actionControl.setText(_translate("OpenFOAM", "Control "))
        self.actionz.setText(_translate("OpenFOAM", "z=="))
        self.actionSplit_region.setText(_translate("OpenFOAM", "Split region"))
        self.actionMuti_region.setText(_translate("OpenFOAM", "Muti region"))
        self.actionFluid.setText(_translate("OpenFOAM", "Fluid"))
        self.actionSolid.setText(_translate("OpenFOAM", "Solid"))
        self.actionNote.setText(_translate("OpenFOAM", "Note"))
        self.actionRun.setText(_translate("OpenFOAM", "Run"))
        self.actionStop.setText(_translate("OpenFOAM", "Stop"))
        self.actionPostProcess.setText(_translate("OpenFOAM", "PostProcess"))
        self.actionAlign_X.setText(_translate("OpenFOAM", "Align X+"))
        self.actionAlign_X_2.setText(_translate("OpenFOAM", "Align X-"))
        self.actionAlign_Y.setText(_translate("OpenFOAM", "Align Y+"))
        self.actionAligh_Y.setText(_translate("OpenFOAM", "Aligh Y-"))
        self.actionAligh_Z.setText(_translate("OpenFOAM", "Aligh Z+"))
        self.actionAligh_Z_2.setText(_translate("OpenFOAM", "Aligh Z-"))
        self.actionAlign_45.setText(_translate("OpenFOAM", "Align 45°"))
import icons_rc
