# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createCylinder.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_createCylinder(object):
    def setupUi(self, createCylinder):
        createCylinder.setObjectName("createCylinder")
        createCylinder.resize(215, 210)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(createCylinder)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(createCylinder)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(createCylinder)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.cylinderNameInput = QtWidgets.QLineEdit(createCylinder)
        self.cylinderNameInput.setObjectName("cylinderNameInput")
        self.gridLayout.addWidget(self.cylinderNameInput, 0, 1, 1, 1)
        self.cylinderColorCombox = QtWidgets.QComboBox(createCylinder)
        self.cylinderColorCombox.setObjectName("cylinderColorCombox")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.cylinderColorCombox.addItem("")
        self.gridLayout.addWidget(self.cylinderColorCombox, 1, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(createCylinder)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 0, 1, 1)
        self.cylinderResoluInput = QtWidgets.QLineEdit(createCylinder)
        self.cylinderResoluInput.setObjectName("cylinderResoluInput")
        self.gridLayout.addWidget(self.cylinderResoluInput, 2, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(createCylinder)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_4 = QtWidgets.QLabel(createCylinder)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label = QtWidgets.QLabel(createCylinder)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.cylinderRadiusInput = QtWidgets.QLineEdit(createCylinder)
        self.cylinderRadiusInput.setObjectName("cylinderRadiusInput")
        self.horizontalLayout_2.addWidget(self.cylinderRadiusInput)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.cylinderHeightInput = QtWidgets.QLineEdit(createCylinder)
        self.cylinderHeightInput.setObjectName("cylinderHeightInput")
        self.verticalLayout_2.addWidget(self.cylinderHeightInput)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.cylinderCenterXInput = QtWidgets.QLineEdit(createCylinder)
        self.cylinderCenterXInput.setObjectName("cylinderCenterXInput")
        self.horizontalLayout.addWidget(self.cylinderCenterXInput)
        self.cylinderCenterYInput = QtWidgets.QLineEdit(createCylinder)
        self.cylinderCenterYInput.setObjectName("cylinderCenterYInput")
        self.horizontalLayout.addWidget(self.cylinderCenterYInput)
        self.cylinderCenterZInpt = QtWidgets.QLineEdit(createCylinder)
        self.cylinderCenterZInpt.setObjectName("cylinderCenterZInpt")
        self.horizontalLayout.addWidget(self.cylinderCenterZInpt)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.previewCylinderBtn = QtWidgets.QPushButton(createCylinder)
        self.previewCylinderBtn.setObjectName("previewCylinderBtn")
        self.horizontalLayout_3.addWidget(self.previewCylinderBtn)
        self.createCylinderBtn = QtWidgets.QPushButton(createCylinder)
        self.createCylinderBtn.setObjectName("createCylinderBtn")
        self.horizontalLayout_3.addWidget(self.createCylinderBtn)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)

        self.retranslateUi(createCylinder)
        QtCore.QMetaObject.connectSlotsByName(createCylinder)

    def retranslateUi(self, createCylinder):
        _translate = QtCore.QCoreApplication.translate
        createCylinder.setWindowTitle(_translate("createCylinder", "Form"))
        self.label_3.setText(_translate("createCylinder", "Name"))
        self.label_5.setText(_translate("createCylinder", "Color"))
        self.cylinderNameInput.setText(_translate("createCylinder", "Cylinder_1"))
        self.cylinderColorCombox.setItemText(0, _translate("createCylinder", "blue"))
        self.cylinderColorCombox.setItemText(1, _translate("createCylinder", "darkBlue"))
        self.cylinderColorCombox.setItemText(2, _translate("createCylinder", "gray"))
        self.cylinderColorCombox.setItemText(3, _translate("createCylinder", "darkGray"))
        self.cylinderColorCombox.setItemText(4, _translate("createCylinder", "lightGray"))
        self.cylinderColorCombox.setItemText(5, _translate("createCylinder", "green"))
        self.cylinderColorCombox.setItemText(6, _translate("createCylinder", "darkGreen"))
        self.cylinderColorCombox.setItemText(7, _translate("createCylinder", "cyan"))
        self.cylinderColorCombox.setItemText(8, _translate("createCylinder", "darkCyan"))
        self.cylinderColorCombox.setItemText(9, _translate("createCylinder", "red"))
        self.cylinderColorCombox.setItemText(10, _translate("createCylinder", "darkRed"))
        self.cylinderColorCombox.setItemText(11, _translate("createCylinder", "magenta"))
        self.cylinderColorCombox.setItemText(12, _translate("createCylinder", "darkMagenta"))
        self.cylinderColorCombox.setItemText(13, _translate("createCylinder", "white"))
        self.cylinderColorCombox.setItemText(14, _translate("createCylinder", "black"))
        self.cylinderColorCombox.setItemText(15, _translate("createCylinder", "PICK"))
        self.label_6.setText(_translate("createCylinder", "Resolution"))
        self.cylinderResoluInput.setText(_translate("createCylinder", "10"))
        self.label_2.setText(_translate("createCylinder", "Radius"))
        self.label_4.setText(_translate("createCylinder", "Height"))
        self.label.setText(_translate("createCylinder", "Center"))
        self.cylinderRadiusInput.setText(_translate("createCylinder", "1"))
        self.cylinderHeightInput.setText(_translate("createCylinder", "1"))
        self.cylinderCenterXInput.setText(_translate("createCylinder", "0"))
        self.cylinderCenterYInput.setText(_translate("createCylinder", "0"))
        self.cylinderCenterZInpt.setText(_translate("createCylinder", "0"))
        self.previewCylinderBtn.setText(_translate("createCylinder", "preview"))
        self.createCylinderBtn.setText(_translate("createCylinder", "Create"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    createCylinder = QtWidgets.QWidget()
    ui = Ui_createCylinder()
    ui.setupUi(createCylinder)
    createCylinder.show()
    sys.exit(app.exec_())
