# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fvSolution_GAMG.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(301, 340)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 9, 0, 1, 1)
        self.solverMinIterInput = QtWidgets.QSpinBox(self.groupBox)
        self.solverMinIterInput.setProperty("value", 1)
        self.solverMinIterInput.setObjectName("solverMinIterInput")
        self.gridLayout.addWidget(self.solverMinIterInput, 9, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 7, 0, 1, 1)
        self.mergeLevelInput = QtWidgets.QSpinBox(self.groupBox)
        self.mergeLevelInput.setProperty("value", 1)
        self.mergeLevelInput.setObjectName("mergeLevelInput")
        self.gridLayout.addWidget(self.mergeLevelInput, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.preSweepInput = QtWidgets.QSpinBox(self.groupBox)
        self.preSweepInput.setProperty("value", 0)
        self.preSweepInput.setObjectName("preSweepInput")
        self.gridLayout.addWidget(self.preSweepInput, 5, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 11, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.postSweepInput = QtWidgets.QSpinBox(self.groupBox)
        self.postSweepInput.setProperty("value", 1)
        self.postSweepInput.setObjectName("postSweepInput")
        self.gridLayout.addWidget(self.postSweepInput, 6, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 6, 0, 1, 1)
        self.solverMaxIterInput = QtWidgets.QSpinBox(self.groupBox)
        self.solverMaxIterInput.setProperty("value", 99)
        self.solverMaxIterInput.setObjectName("solverMaxIterInput")
        self.gridLayout.addWidget(self.solverMaxIterInput, 8, 1, 1, 1)
        self.finestSweepInput = QtWidgets.QSpinBox(self.groupBox)
        self.finestSweepInput.setProperty("value", 2)
        self.finestSweepInput.setObjectName("finestSweepInput")
        self.gridLayout.addWidget(self.finestSweepInput, 7, 1, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 12, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 11, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 12, 0, 1, 1)
        self.cellsCoarseLevelInput = QtWidgets.QSpinBox(self.groupBox)
        self.cellsCoarseLevelInput.setProperty("value", 10)
        self.cellsCoarseLevelInput.setObjectName("cellsCoarseLevelInput")
        self.gridLayout.addWidget(self.cellsCoarseLevelInput, 3, 1, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout.addWidget(self.comboBox_2, 2, 1, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.gridLayout.addWidget(self.checkBox, 1, 1, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.groupBox)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout.addWidget(self.comboBox, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox.setTitle(_translate("Form", "Solver Configuration"))
        self.label_3.setText(_translate("Form", "Cells in Coarsest Level"))
        self.label_2.setText(_translate("Form", "Cache Alggomeration"))
        self.label_13.setText(_translate("Form", "Min Iteration"))
        self.label_12.setText(_translate("Form", "Agglomerator "))
        self.label_10.setText(_translate("Form", "Finest Sweeps"))
        self.label_8.setText(_translate("Form", "Pre Sweeps"))
        self.label.setText(_translate("Form", "Smoother"))
        self.label_5.setText(_translate("Form", "Max Iterations"))
        self.lineEdit.setText(_translate("Form", "1e-6"))
        self.label_4.setText(_translate("Form", "Merge Levels"))
        self.label_9.setText(_translate("Form", "Post Sweeps"))
        self.lineEdit_2.setText(_translate("Form", "1e-2"))
        self.label_6.setText(_translate("Form", "Tolerance"))
        self.label_7.setText(_translate("Form", "Relative Tolerance"))
        self.comboBox_2.setItemText(0, _translate("Form", "Face Area Pair"))
        self.comboBox.setItemText(0, _translate("Form", "Gauss-Seidel"))
        self.comboBox.setItemText(1, _translate("Form", "DIC"))
        self.comboBox.setItemText(2, _translate("Form", "DIC&Gauss-Seidel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
