# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Shaohui/OpenFoam/scripts/PyQtVTK/Ui_Files/Ui_fvSchemes_div.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(276, 533)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.divhInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.divhInput.setObjectName("divhInput")
        self.gridLayout.addWidget(self.divhInput, 3, 1, 1, 1)
        self.divepsilonBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.divepsilonBtn.setCheckable(True)
        self.divepsilonBtn.setObjectName("divepsilonBtn")
        self.gridLayout.addWidget(self.divepsilonBtn, 4, 0, 1, 1)
        self.divpBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.divpBtn.setCheckable(True)
        self.divpBtn.setObjectName("divpBtn")
        self.gridLayout.addWidget(self.divpBtn, 1, 0, 1, 1)
        self.divUInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.divUInput.setObjectName("divUInput")
        self.gridLayout.addWidget(self.divUInput, 0, 1, 1, 1)
        self.divhBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.divhBtn.setCheckable(True)
        self.divhBtn.setObjectName("divhBtn")
        self.gridLayout.addWidget(self.divhBtn, 3, 0, 1, 1)
        self.divUBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.divUBtn.setCheckable(True)
        self.divUBtn.setObjectName("divUBtn")
        self.gridLayout.addWidget(self.divUBtn, 0, 0, 1, 1)
        self.divp_rghBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.divp_rghBtn.setCheckable(True)
        self.divp_rghBtn.setObjectName("divp_rghBtn")
        self.gridLayout.addWidget(self.divp_rghBtn, 2, 0, 1, 1)
        self.divpInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.divpInput.setObjectName("divpInput")
        self.gridLayout.addWidget(self.divpInput, 1, 1, 1, 1)
        self.Inputp_rghInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.Inputp_rghInput.setObjectName("Inputp_rghInput")
        self.gridLayout.addWidget(self.Inputp_rghInput, 2, 1, 1, 1)
        self.divepsilonInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.divepsilonInput.setObjectName("divepsilonInput")
        self.gridLayout.addWidget(self.divepsilonInput, 4, 1, 1, 1)
        self.divkInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.divkInput.setObjectName("divkInput")
        self.gridLayout.addWidget(self.divkInput, 5, 1, 1, 1)
        self.divkBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.divkBtn.setCheckable(True)
        self.divkBtn.setObjectName("divkBtn")
        self.gridLayout.addWidget(self.divkBtn, 5, 0, 1, 1)
        self.divalphatBtn = QtWidgets.QPushButton(self.groupBox_2)
        self.divalphatBtn.setCheckable(True)
        self.divalphatBtn.setObjectName("divalphatBtn")
        self.gridLayout.addWidget(self.divalphatBtn, 6, 0, 1, 1)
        self.divalphatInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.divalphatInput.setObjectName("divalphatInput")
        self.gridLayout.addWidget(self.divalphatInput, 6, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.divUpwindRadChecBox = QtWidgets.QRadioButton(self.groupBox)
        self.divUpwindRadChecBox.setObjectName("divUpwindRadChecBox")
        self.verticalLayout.addWidget(self.divUpwindRadChecBox)
        self.divLinerUpwindChecBox = QtWidgets.QRadioButton(self.groupBox)
        self.divLinerUpwindChecBox.setObjectName("divLinerUpwindChecBox")
        self.verticalLayout.addWidget(self.divLinerUpwindChecBox)
        self.divLinearChecBox = QtWidgets.QRadioButton(self.groupBox)
        self.divLinearChecBox.setObjectName("divLinearChecBox")
        self.verticalLayout.addWidget(self.divLinearChecBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.divLimiteLinearRadBtn = QtWidgets.QRadioButton(self.groupBox)
        self.divLimiteLinearRadBtn.setObjectName("divLimiteLinearRadBtn")
        self.horizontalLayout.addWidget(self.divLimiteLinearRadBtn)
        self.divLimitLinearEffiInput = QtWidgets.QLineEdit(self.groupBox)
        self.divLimitLinearEffiInput.setObjectName("divLimitLinearEffiInput")
        self.horizontalLayout.addWidget(self.divLimitLinearEffiInput)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.divLUSTChecBox = QtWidgets.QRadioButton(self.groupBox)
        self.divLUSTChecBox.setObjectName("divLUSTChecBox")
        self.verticalLayout.addWidget(self.divLUSTChecBox)
        self.divCubicChecBox = QtWidgets.QRadioButton(self.groupBox)
        self.divCubicChecBox.setObjectName("divCubicChecBox")
        self.verticalLayout.addWidget(self.divCubicChecBox)
        self.divVanLeerChecBox = QtWidgets.QRadioButton(self.groupBox)
        self.divVanLeerChecBox.setObjectName("divVanLeerChecBox")
        self.verticalLayout.addWidget(self.divVanLeerChecBox)
        self.divQUICKChecBox = QtWidgets.QRadioButton(self.groupBox)
        self.divQUICKChecBox.setObjectName("divQUICKChecBox")
        self.verticalLayout.addWidget(self.divQUICKChecBox)
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.divBoundedChecBox = QtWidgets.QCheckBox(self.groupBox)
        self.divBoundedChecBox.setObjectName("divBoundedChecBox")
        self.verticalLayout.addWidget(self.divBoundedChecBox)
        self.divSkewCorrectChecBox = QtWidgets.QCheckBox(self.groupBox)
        self.divSkewCorrectChecBox.setObjectName("divSkewCorrectChecBox")
        self.verticalLayout.addWidget(self.divSkewCorrectChecBox)
        self.verticalLayout_2.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "Convect Variables"))
        self.divepsilonBtn.setText(_translate("Form", "epsilon"))
        self.divpBtn.setText(_translate("Form", "p"))
        self.divhBtn.setText(_translate("Form", "h"))
        self.divUBtn.setText(_translate("Form", "U"))
        self.divp_rghBtn.setText(_translate("Form", "p_rgh"))
        self.divkBtn.setText(_translate("Form", "k"))
        self.divalphatBtn.setText(_translate("Form", "alphat"))
        self.groupBox.setTitle(_translate("Form", "div"))
        self.divUpwindRadChecBox.setText(_translate("Form", "Upwind"))
        self.divLinerUpwindChecBox.setText(_translate("Form", "Linear Upwind"))
        self.divLinearChecBox.setText(_translate("Form", "Linear"))
        self.divLimiteLinearRadBtn.setText(_translate("Form", "Limited Linear"))
        self.divLimitLinearEffiInput.setText(_translate("Form", "1"))
        self.divLUSTChecBox.setText(_translate("Form", "LUST"))
        self.divCubicChecBox.setText(_translate("Form", "Cubic"))
        self.divVanLeerChecBox.setText(_translate("Form", "van Leer"))
        self.divQUICKChecBox.setText(_translate("Form", "QUICK"))
        self.divBoundedChecBox.setText(_translate("Form", "Bounded"))
        self.divSkewCorrectChecBox.setText(_translate("Form", "Skew Corrected"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
