# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Shaohui/OpenFoam/scripts/PyQtVTK/Ui_fvSolution_resi_relexa.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(171, 235)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 6, 0, 1, 1)
        self.relexaprghInput = QtWidgets.QLineEdit(Form)
        self.relexaprghInput.setObjectName("relexaprghInput")
        self.gridLayout.addWidget(self.relexaprghInput, 1, 2, 1, 1)
        self.resikInput = QtWidgets.QLineEdit(Form)
        self.resikInput.setObjectName("resikInput")
        self.gridLayout.addWidget(self.resikInput, 5, 1, 1, 1)
        self.relexaILambdaInput = QtWidgets.QLineEdit(Form)
        self.relexaILambdaInput.setObjectName("relexaILambdaInput")
        self.gridLayout.addWidget(self.relexaILambdaInput, 7, 2, 1, 1)
        self.resihFluidInput = QtWidgets.QLineEdit(Form)
        self.resihFluidInput.setObjectName("resihFluidInput")
        self.gridLayout.addWidget(self.resihFluidInput, 3, 1, 1, 1)
        self.relexaUInput = QtWidgets.QLineEdit(Form)
        self.relexaUInput.setObjectName("relexaUInput")
        self.gridLayout.addWidget(self.relexaUInput, 2, 2, 1, 1)
        self.resiepsilonInput = QtWidgets.QLineEdit(Form)
        self.resiepsilonInput.setObjectName("resiepsilonInput")
        self.gridLayout.addWidget(self.resiepsilonInput, 6, 1, 1, 1)
        self.resihSolidInput = QtWidgets.QLineEdit(Form)
        self.resihSolidInput.setObjectName("resihSolidInput")
        self.gridLayout.addWidget(self.resihSolidInput, 8, 1, 1, 1)
        self.lieEdit = QtWidgets.QLineEdit(Form)
        self.lieEdit.setEnabled(False)
        self.lieEdit.setText("")
        self.lieEdit.setObjectName("lieEdit")
        self.gridLayout.addWidget(self.lieEdit, 4, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 8, 0, 1, 1)
        self.resiILambdaInput = QtWidgets.QLineEdit(Form)
        self.resiILambdaInput.setObjectName("resiILambdaInput")
        self.gridLayout.addWidget(self.resiILambdaInput, 7, 1, 1, 1)
        self.resiprghInput = QtWidgets.QLineEdit(Form)
        self.resiprghInput.setObjectName("resiprghInput")
        self.gridLayout.addWidget(self.resiprghInput, 1, 1, 1, 1)
        self.relexakInput = QtWidgets.QLineEdit(Form)
        self.relexakInput.setObjectName("relexakInput")
        self.gridLayout.addWidget(self.relexakInput, 5, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 0, 1, 1, 1)
        self.relexaepsilonInput = QtWidgets.QLineEdit(Form)
        self.relexaepsilonInput.setObjectName("relexaepsilonInput")
        self.gridLayout.addWidget(self.relexaepsilonInput, 6, 2, 1, 1)
        self.resiUInput = QtWidgets.QLineEdit(Form)
        self.resiUInput.setObjectName("resiUInput")
        self.gridLayout.addWidget(self.resiUInput, 2, 1, 1, 1)
        self.resirhoInput = QtWidgets.QLineEdit(Form)
        self.resirhoInput.setObjectName("resirhoInput")
        self.gridLayout.addWidget(self.resirhoInput, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 2, 0, 1, 1)
        self.relexahSolidInput = QtWidgets.QLineEdit(Form)
        self.relexahSolidInput.setObjectName("relexahSolidInput")
        self.gridLayout.addWidget(self.relexahSolidInput, 8, 2, 1, 1)
        self.relexahFluidInput = QtWidgets.QLineEdit(Form)
        self.relexahFluidInput.setObjectName("relexahFluidInput")
        self.gridLayout.addWidget(self.relexahFluidInput, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setText("")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_13.setText(_translate("Form", "Relexation"))
        self.label_5.setText(_translate("Form", "ILambda"))
        self.label_8.setText(_translate("Form", "epsilon"))
        self.relexaprghInput.setText(_translate("Form", "0.7"))
        self.resikInput.setText(_translate("Form", "1E-4"))
        self.relexaILambdaInput.setText(_translate("Form", "0.7"))
        self.resihFluidInput.setText(_translate("Form", "1E-6"))
        self.relexaUInput.setText(_translate("Form", "0.3"))
        self.resiepsilonInput.setText(_translate("Form", "1E-4"))
        self.resihSolidInput.setText(_translate("Form", "1E-6"))
        self.label_4.setText(_translate("Form", "h(solid)"))
        self.resiILambdaInput.setText(_translate("Form", "1E-3"))
        self.resiprghInput.setText(_translate("Form", "1E-6"))
        self.relexakInput.setText(_translate("Form", "0.5"))
        self.label_10.setText(_translate("Form", "p_rgh"))
        self.label_12.setText(_translate("Form", "Residuals"))
        self.relexaepsilonInput.setText(_translate("Form", "0.5"))
        self.resiUInput.setText(_translate("Form", "1E-6"))
        self.resirhoInput.setText(_translate("Form", "1E-6"))
        self.label.setText(_translate("Form", "U"))
        self.relexahSolidInput.setText(_translate("Form", "1"))
        self.relexahFluidInput.setText(_translate("Form", "0.6"))
        self.label_6.setText(_translate("Form", "k"))
        self.label_3.setText(_translate("Form", "rho"))
        self.label_2.setText(_translate("Form", "h(fluid)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
