# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Shaohui/OpenFoam/scripts/PyQtVTK/Ui_Files/Ui_physicsProperty.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_physicsProperties(object):
    def setupUi(self, physicsProperties):
        physicsProperties.setObjectName("physicsProperties")
        physicsProperties.resize(298, 464)
        physicsProperties.setMouseTracking(False)
        physicsProperties.setTabletTracking(False)
        physicsProperties.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        physicsProperties.setAcceptDrops(False)
        physicsProperties.setWindowTitle("Form")
        self.verticalLayout = QtWidgets.QVBoxLayout(physicsProperties)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(physicsProperties)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(physicsProperties)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(-1, 1, -1, 1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.radioButton = QtWidgets.QRadioButton(self.frame)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout.addWidget(self.radioButton_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(physicsProperties)
        self.frame_2.setTabletTracking(True)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_4.setContentsMargins(9, 3, 9, 1)
        self.horizontalLayout_4.setSpacing(2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_4.addWidget(self.label_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_5.addWidget(self.radioButton_3)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_2)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_5.addWidget(self.radioButton_4)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_5)
        self.verticalLayout.addWidget(self.frame_2)
        self.groupBox_3 = QtWidgets.QGroupBox(physicsProperties)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName("gridLayout")
        self.TurbuleChecBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.TurbuleChecBox.setObjectName("TurbuleChecBox")
        self.gridLayout.addWidget(self.TurbuleChecBox, 0, 0, 1, 1)
        self.RadiateChecBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.RadiateChecBox.setStyleSheet("QCheckBox.indicator { width: 10px; height: 10px;}")
        self.RadiateChecBox.setObjectName("RadiateChecBox")
        self.gridLayout.addWidget(self.RadiateChecBox, 0, 1, 1, 1)
        self.MultiphaseChecBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.MultiphaseChecBox.setObjectName("MultiphaseChecBox")
        self.gridLayout.addWidget(self.MultiphaseChecBox, 1, 0, 1, 1)
        self.DynaMeshChecBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.DynaMeshChecBox.setObjectName("DynaMeshChecBox")
        self.gridLayout.addWidget(self.DynaMeshChecBox, 1, 1, 1, 1)
        self.MRFChecBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.MRFChecBox.setObjectName("MRFChecBox")
        self.gridLayout.addWidget(self.MRFChecBox, 2, 0, 1, 1)
        self.LagranChecBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.LagranChecBox.setObjectName("LagranChecBox")
        self.gridLayout.addWidget(self.LagranChecBox, 2, 1, 1, 1)
        self.HeatTransferChecBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.HeatTransferChecBox.setObjectName("HeatTransferChecBox")
        self.gridLayout.addWidget(self.HeatTransferChecBox, 3, 0, 1, 1)
        self.BuoyancyChecBox = QtWidgets.QCheckBox(self.groupBox_3)
        self.BuoyancyChecBox.setObjectName("BuoyancyChecBox")
        self.gridLayout.addWidget(self.BuoyancyChecBox, 3, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.selectSolverLabel = QtWidgets.QLabel(physicsProperties)
        self.selectSolverLabel.setObjectName("selectSolverLabel")
        self.horizontalLayout_3.addWidget(self.selectSolverLabel)
        self.selectedSolver = QtWidgets.QLabel(physicsProperties)
        self.selectedSolver.setObjectName("selectedSolver")
        self.horizontalLayout_3.addWidget(self.selectedSolver)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.listWidget = QtWidgets.QListWidget(physicsProperties)
        self.listWidget.setEnabled(True)
        self.listWidget.setObjectName("listWidget")
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        self.verticalLayout.addWidget(self.listWidget)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton = QtWidgets.QPushButton(physicsProperties)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_6.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(physicsProperties)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_6.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout_6)

        self.retranslateUi(physicsProperties)
        QtCore.QMetaObject.connectSlotsByName(physicsProperties)

    def retranslateUi(self, physicsProperties):
        _translate = QtCore.QCoreApplication.translate
        self.label.setText(_translate("physicsProperties", "Solver Selection"))
        self.label_2.setText(_translate("physicsProperties", "Time"))
        self.radioButton.setText(_translate("physicsProperties", "Steady State   "))
        self.radioButton_2.setText(_translate("physicsProperties", "Transient    "))
        self.label_3.setText(_translate("physicsProperties", "Flow"))
        self.radioButton_3.setText(_translate("physicsProperties", "Incompressible"))
        self.radioButton_4.setText(_translate("physicsProperties", "Compresible"))
        self.groupBox_3.setTitle(_translate("physicsProperties", "Physics"))
        self.TurbuleChecBox.setText(_translate("physicsProperties", "Turbulence"))
        self.RadiateChecBox.setText(_translate("physicsProperties", "Radiation"))
        self.MultiphaseChecBox.setText(_translate("physicsProperties", "Multiphase"))
        self.DynaMeshChecBox.setText(_translate("physicsProperties", "Dynamic Mesh"))
        self.MRFChecBox.setText(_translate("physicsProperties", "MRF"))
        self.LagranChecBox.setText(_translate("physicsProperties", "Lagrangian"))
        self.HeatTransferChecBox.setText(_translate("physicsProperties", "Heat Transfer"))
        self.BuoyancyChecBox.setText(_translate("physicsProperties", "Buoyancy"))
        self.selectSolverLabel.setText(_translate("physicsProperties", "    Solvers:"))
        self.selectedSolver.setText(_translate("physicsProperties", " "))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("physicsProperties", "laplacianFoam"))
        item = self.listWidget.item(1)
        item.setText(_translate("physicsProperties", "potentialFoam"))
        item = self.listWidget.item(2)
        item.setText(_translate("physicsProperties", "icoFoam"))
        item = self.listWidget.item(3)
        item.setText(_translate("physicsProperties", "pimpleFoam"))
        item = self.listWidget.item(4)
        item.setText(_translate("physicsProperties", "SRFPimpleFoam"))
        item = self.listWidget.item(5)
        item.setText(_translate("physicsProperties", "pisoFoam"))
        item = self.listWidget.item(6)
        item.setText(_translate("physicsProperties", "simpleFoam"))
        item = self.listWidget.item(7)
        item.setText(_translate("physicsProperties", "rhoPimpleFoam"))
        item = self.listWidget.item(8)
        item.setText(_translate("physicsProperties", "interFoam"))
        item = self.listWidget.item(9)
        item.setText(_translate("physicsProperties", "multiphaseEulerFoam"))
        item = self.listWidget.item(10)
        item.setText(_translate("physicsProperties", "multiphaseInterFoam"))
        item = self.listWidget.item(11)
        item.setText(_translate("physicsProperties", "buoyantBoussinesqPimpleFoam"))
        item = self.listWidget.item(12)
        item.setText(_translate("physicsProperties", "buoyantBoussinesqSimpleFoam"))
        item = self.listWidget.item(13)
        item.setText(_translate("physicsProperties", "buoyantPimpleFoam"))
        item = self.listWidget.item(14)
        item.setText(_translate("physicsProperties", "buoyantSimpleFoam"))
        item = self.listWidget.item(15)
        item.setText(_translate("physicsProperties", "chtMultiRegionFoam"))
        item = self.listWidget.item(16)
        item.setText(_translate("physicsProperties", "chtMultiRegionSimpleFoam"))
        item = self.listWidget.item(17)
        item.setText(_translate("physicsProperties", "thermoFoam"))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("physicsProperties", "Select"))
        self.pushButton_2.setText(_translate("physicsProperties", "Remove"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    physicsProperties = QtWidgets.QWidget()
    ui = Ui_physicsProperties()
    ui.setupUi(physicsProperties)
    physicsProperties.show()
    sys.exit(app.exec_())
