# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Shaohui/OpenFoam/scripts/PyQtVTK/Ui_Files/Ui_qualityCriteria.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(198, 481)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setObjectName("label_11")
        self.verticalLayout.addWidget(self.label_11)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.label_12)
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setObjectName("label_13")
        self.verticalLayout.addWidget(self.label_13)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setObjectName("label_15")
        self.verticalLayout.addWidget(self.label_15)
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setObjectName("label_16")
        self.verticalLayout.addWidget(self.label_16)
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.label_18 = QtWidgets.QLabel(Form)
        self.label_18.setObjectName("label_18")
        self.verticalLayout.addWidget(self.label_18)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.maxNonOrthoInput = QtWidgets.QLineEdit(Form)
        self.maxNonOrthoInput.setObjectName("maxNonOrthoInput")
        self.verticalLayout_2.addWidget(self.maxNonOrthoInput)
        self.relaxNonOrthoInput = QtWidgets.QLineEdit(Form)
        self.relaxNonOrthoInput.setObjectName("relaxNonOrthoInput")
        self.verticalLayout_2.addWidget(self.relaxNonOrthoInput)
        self.maxBoundarySkewInput = QtWidgets.QLineEdit(Form)
        self.maxBoundarySkewInput.setObjectName("maxBoundarySkewInput")
        self.verticalLayout_2.addWidget(self.maxBoundarySkewInput)
        self.maxInterSkewInput = QtWidgets.QLineEdit(Form)
        self.maxInterSkewInput.setObjectName("maxInterSkewInput")
        self.verticalLayout_2.addWidget(self.maxInterSkewInput)
        self.maxConcaveInput = QtWidgets.QLineEdit(Form)
        self.maxConcaveInput.setObjectName("maxConcaveInput")
        self.verticalLayout_2.addWidget(self.maxConcaveInput)
        self.minVolInput = QtWidgets.QLineEdit(Form)
        self.minVolInput.setObjectName("minVolInput")
        self.verticalLayout_2.addWidget(self.minVolInput)
        self.minTetqualityInput = QtWidgets.QLineEdit(Form)
        self.minTetqualityInput.setObjectName("minTetqualityInput")
        self.verticalLayout_2.addWidget(self.minTetqualityInput)
        self.minAreaInput = QtWidgets.QLineEdit(Form)
        self.minAreaInput.setObjectName("minAreaInput")
        self.verticalLayout_2.addWidget(self.minAreaInput)
        self.minTwistInput = QtWidgets.QLineEdit(Form)
        self.minTwistInput.setObjectName("minTwistInput")
        self.verticalLayout_2.addWidget(self.minTwistInput)
        self.minDeterminInput = QtWidgets.QLineEdit(Form)
        self.minDeterminInput.setObjectName("minDeterminInput")
        self.verticalLayout_2.addWidget(self.minDeterminInput)
        self.minFaceWeightInput = QtWidgets.QLineEdit(Form)
        self.minFaceWeightInput.setObjectName("minFaceWeightInput")
        self.verticalLayout_2.addWidget(self.minFaceWeightInput)
        self.minVolRatioInput = QtWidgets.QLineEdit(Form)
        self.minVolRatioInput.setObjectName("minVolRatioInput")
        self.verticalLayout_2.addWidget(self.minVolRatioInput)
        self.minTriagTwistInput = QtWidgets.QLineEdit(Form)
        self.minTriagTwistInput.setObjectName("minTriagTwistInput")
        self.verticalLayout_2.addWidget(self.minTriagTwistInput)
        self.minVolCollapRatioInput = QtWidgets.QLineEdit(Form)
        self.minVolCollapRatioInput.setObjectName("minVolCollapRatioInput")
        self.verticalLayout_2.addWidget(self.minVolCollapRatioInput)
        self.spinBox = QtWidgets.QSpinBox(Form)
        self.spinBox.setProperty("value", 4)
        self.spinBox.setObjectName("spinBox")
        self.verticalLayout_2.addWidget(self.spinBox)
        self.errorReductInput = QtWidgets.QLineEdit(Form)
        self.errorReductInput.setObjectName("errorReductInput")
        self.verticalLayout_2.addWidget(self.errorReductInput)
        self.mergeTolerInput = QtWidgets.QLineEdit(Form)
        self.mergeTolerInput.setObjectName("mergeTolerInput")
        self.verticalLayout_2.addWidget(self.mergeTolerInput)
        self.geoMatchChecBox = QtWidgets.QCheckBox(Form)
        self.geoMatchChecBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.geoMatchChecBox.setText("")
        self.geoMatchChecBox.setObjectName("geoMatchChecBox")
        self.verticalLayout_2.addWidget(self.geoMatchChecBox)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Max Non-Orthogonality"))
        self.label_4.setText(_translate("Form", "Relax Non-Orthogonal"))
        self.label_6.setText(_translate("Form", "Max Boundary Skewnes"))
        self.label_2.setText(_translate("Form", "Max Internal Skewness"))
        self.label_3.setText(_translate("Form", "Max Concave"))
        self.label_5.setText(_translate("Form", "Min Volume"))
        self.label_9.setText(_translate("Form", "Min Tet Quality"))
        self.label_7.setText(_translate("Form", "Min Area"))
        self.label_8.setText(_translate("Form", "Min Twist"))
        self.label_10.setText(_translate("Form", "Min Determinant"))
        self.label_11.setText(_translate("Form", "Min Face Weight"))
        self.label_12.setText(_translate("Form", "Min Vol Ratio"))
        self.label_13.setText(_translate("Form", "Min Triangle Twist"))
        self.label_14.setText(_translate("Form", "Min Vol Collapse Ratio"))
        self.label_15.setText(_translate("Form", "Smooth Iterations"))
        self.label_16.setText(_translate("Form", "Error Reduction"))
        self.label_17.setText(_translate("Form", "Merge Tolerance"))
        self.label_18.setText(_translate("Form", "Geometric Match"))
        self.maxNonOrthoInput.setText(_translate("Form", "65"))
        self.relaxNonOrthoInput.setText(_translate("Form", "75"))
        self.maxBoundarySkewInput.setText(_translate("Form", "20"))
        self.maxInterSkewInput.setText(_translate("Form", "4"))
        self.maxConcaveInput.setText(_translate("Form", "80"))
        self.minVolInput.setText(_translate("Form", "1e-14"))
        self.minTetqualityInput.setText(_translate("Form", "1e-20"))
        self.minAreaInput.setText(_translate("Form", "-1"))
        self.minTwistInput.setText(_translate("Form", "0.02"))
        self.minDeterminInput.setText(_translate("Form", "0.01"))
        self.minFaceWeightInput.setText(_translate("Form", "0.05"))
        self.minVolRatioInput.setText(_translate("Form", "1e-2"))
        self.minTriagTwistInput.setText(_translate("Form", "-1"))
        self.minVolCollapRatioInput.setText(_translate("Form", "0.1"))
        self.errorReductInput.setText(_translate("Form", "0.75"))
        self.mergeTolerInput.setText(_translate("Form", "1e-7"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
