# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Shaohui/OpenFoam/scripts/PyQtVTK/Ui_Files/Ui_snappy.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(260, 591)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mergeTolerInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.mergeTolerInput.setObjectName("mergeTolerInput")
        self.gridLayout_2.addWidget(self.mergeTolerInput, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 13, 0, 1, 1)
        self.tolerenceInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.tolerenceInput.setObjectName("tolerenceInput")
        self.gridLayout_2.addWidget(self.tolerenceInput, 4, 4, 1, 1)
        self.edgeSnappIterSpix = QtWidgets.QSpinBox(self.groupBox_2)
        self.edgeSnappIterSpix.setProperty("value", 5)
        self.edgeSnappIterSpix.setObjectName("edgeSnappIterSpix")
        self.gridLayout_2.addWidget(self.edgeSnappIterSpix, 10, 4, 1, 1)
        self.implicitFeatureSnapChecBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.implicitFeatureSnapChecBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.implicitFeatureSnapChecBox.setText("")
        self.implicitFeatureSnapChecBox.setChecked(True)
        self.implicitFeatureSnapChecBox.setObjectName("implicitFeatureSnapChecBox")
        self.gridLayout_2.addWidget(self.implicitFeatureSnapChecBox, 15, 4, 1, 1)
        self.explicitFeatureSnapChecBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.explicitFeatureSnapChecBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.explicitFeatureSnapChecBox.setText("")
        self.explicitFeatureSnapChecBox.setChecked(True)
        self.explicitFeatureSnapChecBox.setObjectName("explicitFeatureSnapChecBox")
        self.gridLayout_2.addWidget(self.explicitFeatureSnapChecBox, 16, 4, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.groupBox_2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_2.addWidget(self.label_18, 15, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.groupBox_2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 17, 0, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.groupBox_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox_2)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.relexaIterSpix = QtWidgets.QSpinBox(self.groupBox_2)
        self.relexaIterSpix.setProperty("value", 5)
        self.relexaIterSpix.setObjectName("relexaIterSpix")
        self.gridLayout_2.addWidget(self.relexaIterSpix, 8, 4, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.groupBox_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 18, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 8, 0, 1, 3)
        self.combineFaceChecBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.combineFaceChecBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.combineFaceChecBox.setText("")
        self.combineFaceChecBox.setChecked(True)
        self.combineFaceChecBox.setObjectName("combineFaceChecBox")
        self.gridLayout_2.addWidget(self.combineFaceChecBox, 2, 4, 1, 1)
        self.dispIterSpix = QtWidgets.QSpinBox(self.groupBox_2)
        self.dispIterSpix.setProperty("value", 3)
        self.dispIterSpix.setObjectName("dispIterSpix")
        self.gridLayout_2.addWidget(self.dispIterSpix, 6, 4, 1, 1)
        self.faceSplitInterSpix = QtWidgets.QSpinBox(self.groupBox_2)
        self.faceSplitInterSpix.setProperty("value", 5)
        self.faceSplitInterSpix.setObjectName("faceSplitInterSpix")
        self.gridLayout_2.addWidget(self.faceSplitInterSpix, 17, 4, 1, 1)
        self.featureAngInput = QtWidgets.QLineEdit(self.groupBox_2)
        self.featureAngInput.setObjectName("featureAngInput")
        self.gridLayout_2.addWidget(self.featureAngInput, 18, 4, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.groupBox_2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 19, 0, 1, 2)
        self.featureRefineSpix = QtWidgets.QSpinBox(self.groupBox_2)
        self.featureRefineSpix.setObjectName("featureRefineSpix")
        self.gridLayout_2.addWidget(self.featureRefineSpix, 19, 4, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 3, 0, 1, 5)
        self.smoothIterSpix = QtWidgets.QSpinBox(self.groupBox_2)
        self.smoothIterSpix.setMaximum(10000)
        self.smoothIterSpix.setProperty("value", 500)
        self.smoothIterSpix.setObjectName("smoothIterSpix")
        self.gridLayout_2.addWidget(self.smoothIterSpix, 5, 4, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 6, 0, 1, 4)
        self.multiRegionFeatureSnapChecBox = QtWidgets.QCheckBox(self.groupBox_2)
        self.multiRegionFeatureSnapChecBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.multiRegionFeatureSnapChecBox.setText("")
        self.multiRegionFeatureSnapChecBox.setChecked(True)
        self.multiRegionFeatureSnapChecBox.setObjectName("multiRegionFeatureSnapChecBox")
        self.gridLayout_2.addWidget(self.multiRegionFeatureSnapChecBox, 13, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 16, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 4, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.groupBox_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 10, 0, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.groupBox)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.maxLocalCellInput = QtWidgets.QLineEdit(self.groupBox)
        self.maxLocalCellInput.setObjectName("maxLocalCellInput")
        self.gridLayout.addWidget(self.maxLocalCellInput, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.groupBox)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 0, 1, 1)
        self.maxGlobalCellInput = QtWidgets.QLineEdit(self.groupBox)
        self.maxGlobalCellInput.setObjectName("maxGlobalCellInput")
        self.gridLayout.addWidget(self.maxGlobalCellInput, 1, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.cellBetweenLevelSpix = QtWidgets.QSpinBox(self.groupBox)
        self.cellBetweenLevelSpix.setProperty("value", 4)
        self.cellBetweenLevelSpix.setObjectName("cellBetweenLevelSpix")
        self.gridLayout.addWidget(self.cellBetweenLevelSpix, 2, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 3, 0, 1, 1)
        self.minRefineCellSpix = QtWidgets.QSpinBox(self.groupBox)
        self.minRefineCellSpix.setProperty("value", 10)
        self.minRefineCellSpix.setObjectName("minRefineCellSpix")
        self.gridLayout.addWidget(self.minRefineCellSpix, 3, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 4, 0, 1, 1)
        self.maxLoadUnbalanInput = QtWidgets.QLineEdit(self.groupBox)
        self.maxLoadUnbalanInput.setObjectName("maxLoadUnbalanInput")
        self.gridLayout.addWidget(self.maxLoadUnbalanInput, 4, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 6, 0, 1, 1)
        self.gapLevelIncreSpix = QtWidgets.QSpinBox(self.groupBox)
        self.gapLevelIncreSpix.setObjectName("gapLevelIncreSpix")
        self.gridLayout.addWidget(self.gapLevelIncreSpix, 6, 1, 1, 1)
        self.freeStandZoneFaceChecBox = QtWidgets.QCheckBox(self.groupBox)
        self.freeStandZoneFaceChecBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.freeStandZoneFaceChecBox.setText("")
        self.freeStandZoneFaceChecBox.setChecked(True)
        self.freeStandZoneFaceChecBox.setObjectName("freeStandZoneFaceChecBox")
        self.gridLayout.addWidget(self.freeStandZoneFaceChecBox, 7, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 7, 0, 1, 1)
        self.gapLevelIncreChecBox = QtWidgets.QCheckBox(self.groupBox)
        self.gapLevelIncreChecBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.gapLevelIncreChecBox.setText("")
        self.gapLevelIncreChecBox.setChecked(True)
        self.gapLevelIncreChecBox.setObjectName("gapLevelIncreChecBox")
        self.gridLayout.addWidget(self.gapLevelIncreChecBox, 5, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.groupBox)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 5, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.groupBox_2.setTitle(_translate("Form", "snap"))
        self.mergeTolerInput.setText(_translate("Form", "1e-6"))
        self.label_2.setText(_translate("Form", "Multiregion Feature Snap"))
        self.tolerenceInput.setText(_translate("Form", "1"))
        self.label_5.setText(_translate("Form", "Smooting Iterations"))
        self.label_18.setText(_translate("Form", "Implicit Feature Snap"))
        self.label_12.setText(_translate("Form", "Face Split Interval"))
        self.label_3.setText(_translate("Form", "Combine Faces"))
        self.label.setText(_translate("Form", "Merge Tolerance"))
        self.label_13.setText(_translate("Form", "Feature Angle"))
        self.label_9.setText(_translate("Form", "Relaxation Iterations"))
        self.featureAngInput.setText(_translate("Form", "120"))
        self.label_14.setText(_translate("Form", "Feature Refinement"))
        self.label_4.setText(_translate("Form", "Displacement Iterations"))
        self.label_19.setText(_translate("Form", "Explicit Feature Snap"))
        self.label_6.setText(_translate("Form", "Tolerence"))
        self.label_11.setText(_translate("Form", "Edge Snapping Iterations"))
        self.groupBox.setTitle(_translate("Form", "Refinement"))
        self.label_7.setText(_translate("Form", "Max Local Cells"))
        self.maxLocalCellInput.setText(_translate("Form", "1000000"))
        self.label_8.setText(_translate("Form", "Max Global Cells"))
        self.maxGlobalCellInput.setText(_translate("Form", "100000000"))
        self.label_10.setText(_translate("Form", "Cells Between Levels"))
        self.label_15.setText(_translate("Form", "Min Refinement Cells"))
        self.label_16.setText(_translate("Form", "Max Load Unbalance"))
        self.maxLoadUnbalanInput.setText(_translate("Form", "0.1"))
        self.label_17.setText(_translate("Form", "Gap Level Increment"))
        self.label_20.setText(_translate("Form", "Free Standing Zone Faces    "))
        self.gapLevelIncreChecBox.setToolTip(_translate("Form", "This is a test"))
        self.gapLevelIncreChecBox.setStatusTip(_translate("Form", "This is a test"))
        self.label_21.setText(_translate("Form", "Use Gap Level Increment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
